import{a as v,S as b,i as n}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))f(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&f(d)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function f(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const S="52575025-ab19d41e2843e5421c049623c",q="https://pixabay.com/api/";async function g(r,t=1){try{return(await v.get(q,{params:{key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}catch{throw new Error("Failed to fetch images")}}let P=new b(".gallery a");const m=document.querySelector(".gallery"),c=document.querySelector(".loader"),l=document.querySelector(".load-more");function h(r){const t=r.map(o=>`
      <li class="gallery-item">
        <a href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
        </a>
        <div class="image-stats">
          <span>Likes <strong>${o.likes}</strong></span>
          <span>Views <strong>${o.views}</strong></span>
          <span>Comments <strong>${o.comments}</strong></span>
          <span>Downloads <strong>${o.downloads}</strong></span>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",t),P.refresh()}function R(){m.innerHTML=""}function p(){c&&c.classList.remove("is-hidden")}function y(){c&&c.classList.add("is-hidden")}function E(){l&&l.classList.remove("is-hidden")}function L(){l&&l.classList.add("is-hidden")}const w=document.querySelector(".form"),B=w.querySelector('input[name="search-text"]'),$=document.querySelector(".load-more");let i=1,a="",u=0;w.addEventListener("submit",async r=>{if(r.preventDefault(),a=B.value.trim(),i=1,a===""){n.warning({title:"Warning",message:"Please enter a search term.",position:"topRight"});return}R(),L(),p();try{const t=await g(a,i);t.hits.length===0?n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"}):(h(t.hits),u=t.totalHits,i*15<u?E():n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}});$.addEventListener("click",async()=>{i++,p();try{const r=await g(a,i);h(r.hits),i*15>=u&&(L(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),M()}catch{n.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{y()}});function M(){const r=document.querySelector(".gallery-item");if(r){const t=r.getBoundingClientRect();window.scrollBy({top:t.height*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
