import{a as b,S as E,i as n}from"./assets/vendor-BNibzuFn.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))h(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&h(f)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function h(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const P="52575025-ab19d41e2843e5421c049623c",R="https://pixabay.com/api/";async function p(o,e=1){try{return(await b.get(R,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})).data}catch{throw new Error("Failed to fetch images")}}let q=new E(".gallery a");const y=document.querySelector(".gallery"),c=document.querySelector(".loader"),d=document.querySelector(".load-more");function L(o){const e=o.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        </a>
        <div class="image-stats">
          <span>Likes <strong>${r.likes}</strong></span>
          <span>Views <strong>${r.views}</strong></span>
          <span>Comments <strong>${r.comments}</strong></span>
          <span>Downloads <strong>${r.downloads}</strong></span>
        </div>
      </li>
    `).join("");y.insertAdjacentHTML("beforeend",e),q.refresh()}function I(){y.innerHTML=""}function w(){c&&c.classList.remove("is-hidden")}function v(){c&&c.classList.add("is-hidden")}function m(){d&&d.classList.remove("is-hidden")}function u(){d&&d.classList.add("is-hidden")}const S=document.querySelector(".form"),$=S.querySelector('input[name="search-text"]'),B=document.querySelector(".load-more"),C=document.querySelector(".gallery"),M=15;let g=1,l="",a=0,i=0;u();S.addEventListener("submit",async o=>{if(o.preventDefault(),l=$.value.trim(),g=1,a=0,i=0,l===""){n.warning({title:"Warning",message:"Please enter a search term.",position:"topRight"});return}I(),u(),w();try{const e=await p(l,g);a=e.totalHits;const r=e.hits.length;i=r,r===0?n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"}):(L(e.hits),i<a?m():n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{v()}});B.addEventListener("click",async()=>{u(),w(),g++;try{const o=await p(l,g),e=o.hits.length;e>0&&(L(o.hits),i+=e,A()),e<M||i>=a?(u(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):m()}catch{n.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),i<a&&m()}finally{v()}});function A(){const o=C.firstElementChild;if(o){const e=o.getBoundingClientRect();window.scrollBy({top:e.height*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
